**Задание 1**
*   Создайте матрицу 3 на 3, заполненную числами от 1 до 9
*   Прибавьте к ней матрицу с единицами на диагонале
*   Умножьте полученную матрицу на вектор (1, 2, 3)
*   Вычислить транспонированную матрицу от полученной в результате прибавления матрицы
*   Посчитайте обратную матрицу к полученной в результате прибавления матрице


In [ ]:
import numpy as np

In [ ]:
A1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
A2 = A1 + np.eye(3)
A3 = np.array([1,2,3]) @ A2
A4 = np.transpose(A2)
A5 = np.linalg.inv(A2)
print(f'Начальная матрица A1:\n{A1},\nA1 + единичная матрица:\n{A2},\nМатрица, умноженная на вектор:\n{A3},\nТранспонированная матрица:\n{A4},\nОбратная матрица:\n{A5}')


Начальная матрица A1:
[[1 2 3]
 [4 5 6]
 [7 8 9]],
A1 + единичная матрица:
[[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]],
Матрица, умноженная на вектор:
[31. 38. 45.],
Транспонированная матрица:
[[ 2.  4.  7.]
 [ 2.  6.  8.]
 [ 3.  6. 10.]],
Обратная матрица:
[[-6.00000000e+00 -2.00000000e+00  3.00000000e+00]
 [-1.00000000e+00  5.00000000e-01 -2.33146835e-16]
 [ 5.00000000e+00  1.00000000e+00 -2.00000000e+00]]


**Задание 2**
Найдите собственные значения и собственные вектора матрицы:

In [ ]:
m = np.array([[2, 2],
              [1, 3]])
eig_lambda = np.linalg.eigvals(m)
eig_vec = np.transpose(np.linalg.eig(m)[1])
print(f'Собственные значения матрицы: {eig_lambda},\n1-й собственный вектор матрицы: {eig_vec[0]/0.4472136},\n2-й собственный вектор матрицы: {eig_vec[1]/(-0.70710678)}')

Собственные значения матрицы: [1. 4.],
1-й собственный вектор матрицы: [-1.99999998  0.99999999],
2-й собственный вектор матрицы: [1. 1.]


**Задание 3**
Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

In [ ]:
n = np.array([[-6,-2,1], [-2,-1,-1], [-1,-1,-2]])
det_n = np.linalg.det(n)
print(n)
print(det_n)

[[-6 -2  1]
 [-2 -1 -1]
 [-1 -1 -2]]
1.0000000000000002
